### ISSUE TITLE
Bug | Point Budget Function Cesium Container - 

### ISSUE THREAD

**Issue by MatthewLee-MDDP** [AuScalableDroneCloud/cesium-asdc#2]
There is a bug in the point budget function that when you scroll down to 0 points then back up. the point cloud fails to load back in. 
![image](https://user-images.githubusercontent.com/97568659/161682592-50f03c54-bf2b-40de-9e0d-26958839afcb.png)
![image](https://user-images.githubusercontent.com/97568659/161682676-3cbc6ad8-a540-464d-9ec7-7df33d781695.png)
![image](https://user-images.githubusercontent.com/97568659/161682752-23bccf45-2532-4700-9199-243758778c0b.png)

**Comment by Erfan-Shooraj** [comment]
Thank you for letting me know. This should be fixed now.
